# Build and App
ARG PYTHON_VERSION="3.9.0"
FROM python:$PYTHON_VERSION-slim as build
RUN pip install --no-cache-dir --only-binary :all: -U pip && \
    pip install --no-cache-dir --only-binary :all: -U wheel setuptools check-wheel-contents
WORKDIR /code/
COPY . .
RUN python setup.py bdist_wheel && \
    find dist/ -type f -name *.whl -exec check-wheel-contents {} \; \
    -exec pip install --no-cache-dir {} \; && \
    rm -rf *
CMD ["appy"]
